### ISSUE TITLE
Remove support for double quote strings in the parser

### ISSUE THREAD

**Issue by KwilLuke** [kwilteam/kuneiform#22]
SQlite does not support double quoted strings, and currently our engine will throw an error if you try to pass a double quoted string to a SQL query in Kuneiform. I have already removed double quote styling support in the IDE, so we should also remove support for double quotes in kuneiform (so that way the user can get an error if they try to use double quotes).

**Comment by Yaiba** [comment]
@brennanjl could you make single and double quote clear here for different parts in SQLite, for example: table, column and string

**Comment by brennanjl** [comment]
Double quotes are used for identifiers.  Single quotes are used for strings.

Identifiers:
- Tables
- Columns

example:
- INSERT INTO "table1" ("col1") VALUES ('my_string');

**Comment by Yaiba** [comment]
And also need to remove the `markers` of the Identifier if there are, right now valiad Identifiers markers are:
- '`'
- '[' ']'
- '"'

**Comment by Yaiba** [comment]
This is resolved by #30
