### ISSUE TITLE
action annotation 

### ISSUE THREAD

**Issue by Yaiba** [kwilteam/kuneiform#41]
This is a new syntax for extra metadata on a action, the syntax will be:
`@target_name(attr1=1, attr2='2')` .

When started design annotation, the syntax was:
`@annotation(target="xxx", attrs=[])`
which is not as expressive as the new syntax, I'm open to any feedbacks 🚧 .

----

An example.  
If an action `show_something` need authn, say the authn is handled by KGW, you can write a kuneiform file like this:
```
database test;

@kgw(authn='true')
action show_something() public {
    select * from something;
}
```
Really the attributes depends on the 'target' platform or system, in this case, KGW need an attribute named 'authn'.

---

NOTE:    
So far we've used:
- `#` for index name
- `$` for parameter name(in action declaration) and local variable(inside action)
- `@` for block_variable  inside the action declaration such as `select * from user where address=@caller;`

 But it still feels natural to use `@` for annotations.   

Two other options are:
- just use like `annotation()\n action()`,   which looks weird, the purpose of `annotation`  not clear 
- use another signs like `!` to mark annotation

**Comment by jchappelow** [comment]
Will you give an example in the mustsign case, as to where in the kuniform file this would go if there's some action that needs auth?

**Comment by Yaiba** [comment]
> Will you give an example in the mustsign case, as to where in the kuniform file this would go if there's some action that needs auth?

Just updated in the description, hope it's clear enough

**Comment by jchappelow** [comment]
Thanks that's clear.  But does that make the choice of @ risky for block variable collisions, since target is unknown and open ended?  Is "!" ugly? Or + or _ or anything else?

**Comment by Yaiba** [comment]
> Thanks that's clear. But does that make the choice of @ risky for block variable collisions, since target is unknown and open ended? Is "!" ugly? Or + or _ or anything else?

It actually won't collision, since they work in different scope, annotation works outside the action, block_variable works inside the action.  But it does could cause confusion.

`!` is not that ugly, it's just not that common in programming language, but definitely better than `+` or `-` IMO.  I'm open to change the sign.

I choose `@` since it's naturally means AT something, seems make more sense. Also it's a more common sign, like in Python it's used as decorator.

**Comment by jchappelow** [comment]
> It actually won't collision, since they work in different scope, annotation works outside the action, block_variable works inside the action. But it does could cause confusion.

Ah, in that case it's not bad.  My first choice would have been `#` or something that feels more "comenty" like even `;` or `::`, but I think `@` feels fine here too.
