### ISSUE TITLE
update antlr runtime to 4.13

### ISSUE THREAD

**Issue by Yaiba** [kwilteam/kuneiform#47]
According to https://github.com/antlr/antlr4/releases/tag/4.13.0, there is a dedicated repo to import.

todo:
- change jar version
- change go.mod in kuneiform/sql-grammar-go/action-grammar-go/kwil-db

**Comment by jchappelow** [comment]
Started a long time ago: https://github.com/kwilteam/action-grammar-go/commit/24afd89dfb7ede63446a5a4e10e4a11b65312785
I'm not sure what the status is, I think it was done, but needs lots of updates in dependent repos
